### PR TITLE
Some updates for the column-generation code

### PR DESCRIPTION
**Pull request by yeesian**
Changelog

* added docstrings and comments for following the code
* removed some of the constraints deemed to be redundant (https://github.com/juliayyan/NetworkDesignModels.jl/pull/4/commits/eb05d9ff23cf87f37784cbf169fa1039e4485aa5 and https://github.com/juliayyan/NetworkDesignModels.jl/pull/4/commits/40af3cc39dba839e48f10e0fc324115208d212c3)
* use of JuMP multi-line macros and whitespacing (https://github.com/juliayyan/NetworkDesignModels.jl/pull/4/commits/2f81f6121abb6aef53cd97ec0989a586465758ae)
* removed `initialbudget` from MasterProblem constructor (https://github.com/juliayyan/NetworkDesignModels.jl/pull/4/commits/5d33d7dc64c99780ff77ae6284e407223588dab6)
* introduce a `allcommutelines()` method (https://github.com/juliayyan/NetworkDesignModels.jl/pull/4/commits/a8ad81a78908ce037c2552c07229214fbeff4ea9)
* support multiple callbacks for tracking information (https://github.com/juliayyan/NetworkDesignModels.jl/pull/4/commits/b23728502cba43d13014bee3eee23214914b2692)
* filter out `u` from `nonzerodests(np, u)` (https://github.com/juliayyan/NetworkDesignModels.jl/pull/4/commits/011b7effe757848efb041c2e16408a721fa11cff)

### CODE REVIEW

**Comment by yeesian** [comment]
Okay this is now ready for review.

**Comment by juliayyan** [comment]
This looks great and all tests still pass for me.

**Comment by yeesian** [comment]
Okay for me to squash and merge into the column-generation branch?

**Comment by juliayyan** [comment]
yes!

**Pull request merged**
